### ISSUE TITLE
unrecognized arguments: --local_rank=1

### ISSUE THREAD

**Issue by SunyanGu** [fastnlp/CPT#65]
I have single machine with two GPUs.This errors occurred when I use this command "python -m torch.distributed.launch --nproc_per_node=4 train_adgen.py" to finetune gen model.
The error report below:
usage: train_adgen.py [-h] [--model_path MODEL_PATH] [--dataset DATASET]
                      [--lr LR] [--batch_size BATCH_SIZE] [--epoch EPOCH]
                      [--data_dir DATA_DIR]
train_adgen.py: error: unrecognized arguments: --local_rank=2
usage: train_adgen.py [-h] [--model_path MODEL_PATH] [--dataset DATASET]
                      [--lr LR] [--batch_size BATCH_SIZE] [--epoch EPOCH]
                      [--data_dir DATA_DIR]
train_adgen.py: error: unrecognized arguments: --local_rank=0
usage: train_adgen.py [-h] [--model_path MODEL_PATH] [--dataset DATASET]
                      [--lr LR] [--batch_size BATCH_SIZE] [--epoch EPOCH]
                      [--data_dir DATA_DIR]
train_adgen.py: error: unrecognized arguments: --local_rank=1
Traceback (most recent call last):
  File "/home/user/miniconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/miniconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/miniconda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda/bin/python', '-u', 'train_adgen.py', '--local_rank=2']' returned non-zero exit status 2.

can anyone help me?

**Comment by SunyanGu** [comment]
this problem is resolved ,only need to add parser like:
parser.add_argument("--local_rank", default=0, type=int)
