### ISSUE TITLE
run_gen.py returns UnicodeDecodeError

### ISSUE THREAD

**Issue by shivanraptor** [fastnlp/CPT#84]
The `run_gen.py` script returns `UnicodeDecodeError` when loading the `pytorch_model.bin` from the pre-train script. The command I executed is:

```
python run_gen.py --model_path /path/to/generated/pytorch_model.bin --dataset adgen --data_dir demo_data
```

I narrowed down the problems. The minimal codes are as follows:

```
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("/path/to/pytorch_model.bin") # at line 110, raise UnicodeDecodeError
```
The traceback is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter-raptor/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/jupyter-raptor/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/jupyter-raptor/.local/lib/python3.10/site-packages/transformers/models/bert/tokenization_bert.py", line 218, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/home/jupyter-raptor/.local/lib/python3.10/site-packages/transformers/models/bert/tokenization_bert.py", line 121, in load_vocab
    tokens = reader.readlines()
  File "/opt/tljh/user/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
```

How can I resolve this issue?

Versions:

- transformers 4.28.1
- tokenizers 0.13.3
- Python 3.10.10

**Comment by shivanraptor** [comment]
The error is misleading.

The `BertTokenizer.from_pretrained()` is supposed to take a folder instead of a `bin` file. However, the folder requires tokenizers' config and vocab files to get it working. Yet, the `convert_ckpt.py` script only generates the `pytorch_model.bin`. 

To solve this issue, I copied the original tokenizers' config and vocab files to the folder containing `pytorch_model.bin` and changed the command to:

```
python run_gen.py --model_path /path/to/generated/ --dataset adgen --data_dir demo_data
```
